# Generated by Django 2.0 on 2019-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EcsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=128, verbose_name='项目名')),
                ('ali_account', models.CharField(max_length=64, verbose_name='阿里云账号')),
                ('ali_secrts', models.CharField(max_length=64, verbose_name='阿里云密码')),
                ('ali_region', models.CharField(default='cn-hangzhou', max_length=32, verbose_name='阿里云区域')),
                ('ali_keyid', models.CharField(max_length=64, verbose_name='阿里云ID')),
                ('ali_keysecrt', models.CharField(max_length=64, verbose_name='阿里云Secrts')),
                ('ali_contact', models.CharField(max_length=64, verbose_name='阿里云联系人')),
                ('ali_balance', models.IntegerField(null=True, verbose_name='账户余额')),
                ('p_status', models.CharField(max_length=32, verbose_name='项目状态')),
                ('p_date', models.DateField(verbose_name='上线时间')),
            ],
        ),
        migrations.CreateModel(
            name='RdsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=64, verbose_name='项目名')),
                ('r_aid', models.CharField(max_length=64, verbose_name='实例')),
                ('r_engine', models.CharField(max_length=32, verbose_name='类型')),
                ('r_usage', models.IntegerField()),
                ('r_totalusage', models.IntegerField()),
                ('r_memory', models.IntegerField()),
                ('r_expire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SslInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
