# Generated by Django 2.0 on 2019-03-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20190319_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecsinfo',
            name='cpu',
            field=models.IntegerField(null=True, verbose_name='cpu 个数'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='expireTime',
            field=models.CharField(max_length=32, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='instanceId',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='ECS实例id'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='instanceName',
            field=models.CharField(max_length=32, null=True, verbose_name='ECS实例名字'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='memory',
            field=models.IntegerField(null=True, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='p_name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='项目名'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='pivIp',
            field=models.CharField(max_length=32, null=True, verbose_name='私有IP'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='pubIp',
            field=models.CharField(max_length=32, null=True, verbose_name='公有IP'),
        ),
        migrations.AddField(
            model_name='ecsinfo',
            name='status',
            field=models.CharField(max_length=32, null=True, verbose_name='实例状态'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='p_abbr',
            field=models.CharField(max_length=16, null=True, verbose_name='项目缩写'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='p_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='rdsinfo',
            name='p_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='项目名'),
        ),
    ]
